name: Run test scripts for typescript
on:
  - push
  - workflow_dispatch
defaults:
  run:
    working-directory: ts
jobs:
  creational_patterns_tests:
    runs-on: ubuntu-latest
    name: Run test scripts for creational patterns
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
