name: Run test scripts for typescript
on:
  - push
  - workflow_dispatch
jobs:
  creational_patterns_tests:
    runs-on: ubuntu-latest
    name: Run test scripts for creational patterns
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install dependencies
        working-directory: ts
        run: npm ci
      - name: Run tests
        working-directory: ts
        run: npm test
